CheckpointName = "Illustrious/JANKUV30NoobaiEPSRouwei_v30.safetensors"
ClipSet = -2
VAE = "Use_merged_vae"
PositivePromptA = "masterpiece, best quality"
PositivePromptB = ""
PositivePromptC = ""
NegativePromptA = "worst quality, low quality, watermark"
NegativePromptB = ""
NegativePromptC = ""
Width = 896
Height = 1152
BatchSize = 1
Steps = 26
CFG = "3.0-5.0,5.0"
SamplerName = "euler_ancestral"
Scheduler = "normal"
